// GENERATED by scripts/gen-types.sh from the database schema. Do not edit.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      audit_logs: {
        Row: {
          action: string;
          actor_type: Database["public"]["Enums"]["audit_actor_type"];
          actor_user_id: string | null;
          ai_action_id: string | null;
          changes: Json | null;
          created_at: string;
          entity_id: string | null;
          entity_type: string;
          id: number;
          ip_address: unknown;
          organization_id: string | null;
          request_id: string | null;
          user_agent: string | null;
        };
        Insert: {
          action: string;
          actor_type: Database["public"]["Enums"]["audit_actor_type"];
          actor_user_id?: string | null;
          ai_action_id?: string | null;
          changes?: Json | null;
          created_at?: string;
          entity_id?: string | null;
          entity_type: string;
          id?: never;
          ip_address?: unknown;
          organization_id?: string | null;
          request_id?: string | null;
          user_agent?: string | null;
        };
        Update: {
          action?: string;
          actor_type?: Database["public"]["Enums"]["audit_actor_type"];
          actor_user_id?: string | null;
          ai_action_id?: string | null;
          changes?: Json | null;
          created_at?: string;
          entity_id?: string | null;
          entity_type?: string;
          id?: never;
          ip_address?: unknown;
          organization_id?: string | null;
          request_id?: string | null;
          user_agent?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "audit_logs_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      availability_blocks: {
        Row: {
          created_at: string;
          created_by: string | null;
          id: string;
          inventory_unit_id: string | null;
          notes: string | null;
          organization_id: string;
          period: unknown;
          product_id: string | null;
          quantity: number | null;
          reason: Database["public"]["Enums"]["block_reason"];
          updated_at: string;
          variant_id: string | null;
        };
        Insert: {
          created_at?: string;
          created_by?: string | null;
          id?: string;
          inventory_unit_id?: string | null;
          notes?: string | null;
          organization_id: string;
          period: unknown;
          product_id?: string | null;
          quantity?: number | null;
          reason: Database["public"]["Enums"]["block_reason"];
          updated_at?: string;
          variant_id?: string | null;
        };
        Update: {
          created_at?: string;
          created_by?: string | null;
          id?: string;
          inventory_unit_id?: string | null;
          notes?: string | null;
          organization_id?: string;
          period?: unknown;
          product_id?: string | null;
          quantity?: number | null;
          reason?: Database["public"]["Enums"]["block_reason"];
          updated_at?: string;
          variant_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "availability_blocks_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "availability_blocks_organization_id_inventory_unit_id_fkey";
            columns: ["organization_id", "inventory_unit_id"];
            isOneToOne: false;
            referencedRelation: "inventory_units";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "availability_blocks_organization_id_product_id_fkey";
            columns: ["organization_id", "product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "availability_blocks_organization_id_product_id_fkey";
            columns: ["organization_id", "product_id"];
            isOneToOne: false;
            referencedRelation: "public_catalog_products";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "availability_blocks_organization_id_variant_id_fkey";
            columns: ["organization_id", "variant_id"];
            isOneToOne: false;
            referencedRelation: "product_variants";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      categories: {
        Row: {
          archived_at: string | null;
          created_at: string;
          description: string | null;
          id: string;
          included_duration_minutes: number | null;
          is_published: boolean;
          name: string;
          organization_id: string;
          overnight_allowed: boolean | null;
          parent_id: string | null;
          setup_buffer_minutes: number | null;
          slug: string;
          sort_order: number;
          teardown_buffer_minutes: number | null;
          updated_at: string;
        };
        Insert: {
          archived_at?: string | null;
          created_at?: string;
          description?: string | null;
          id?: string;
          included_duration_minutes?: number | null;
          is_published?: boolean;
          name: string;
          organization_id: string;
          overnight_allowed?: boolean | null;
          parent_id?: string | null;
          setup_buffer_minutes?: number | null;
          slug: string;
          sort_order?: number;
          teardown_buffer_minutes?: number | null;
          updated_at?: string;
        };
        Update: {
          archived_at?: string | null;
          created_at?: string;
          description?: string | null;
          id?: string;
          included_duration_minutes?: number | null;
          is_published?: boolean;
          name?: string;
          organization_id?: string;
          overnight_allowed?: boolean | null;
          parent_id?: string | null;
          setup_buffer_minutes?: number | null;
          slug?: string;
          sort_order?: number;
          teardown_buffer_minutes?: number | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "categories_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "categories_organization_id_parent_id_fkey";
            columns: ["organization_id", "parent_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "categories_organization_id_parent_id_fkey";
            columns: ["organization_id", "parent_id"];
            isOneToOne: false;
            referencedRelation: "public_catalog_categories";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      import_batches: {
        Row: {
          adapter_id: string;
          committed_at: string | null;
          created_at: string;
          created_by: string | null;
          external_source: string;
          headers: string[];
          id: string;
          kind: string;
          mapping: Json | null;
          organization_id: string;
          original_filename: string | null;
          row_count: number;
          status: Database["public"]["Enums"]["import_status"];
          summary: Json | null;
          updated_at: string;
        };
        Insert: {
          adapter_id: string;
          committed_at?: string | null;
          created_at?: string;
          created_by?: string | null;
          external_source: string;
          headers: string[];
          id?: string;
          kind?: string;
          mapping?: Json | null;
          organization_id: string;
          original_filename?: string | null;
          row_count: number;
          status?: Database["public"]["Enums"]["import_status"];
          summary?: Json | null;
          updated_at?: string;
        };
        Update: {
          adapter_id?: string;
          committed_at?: string | null;
          created_at?: string;
          created_by?: string | null;
          external_source?: string;
          headers?: string[];
          id?: string;
          kind?: string;
          mapping?: Json | null;
          organization_id?: string;
          original_filename?: string | null;
          row_count?: number;
          status?: Database["public"]["Enums"]["import_status"];
          summary?: Json | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "import_batches_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      import_mapping_presets: {
        Row: {
          adapter_id: string;
          created_at: string;
          created_by: string | null;
          id: string;
          mapping: NonNullable<Json>;
          name: string;
          organization_id: string;
          updated_at: string;
        };
        Insert: {
          adapter_id: string;
          created_at?: string;
          created_by?: string | null;
          id?: string;
          mapping: NonNullable<Json>;
          name: string;
          organization_id: string;
          updated_at?: string;
        };
        Update: {
          adapter_id?: string;
          created_at?: string;
          created_by?: string | null;
          id?: string;
          mapping?: NonNullable<Json>;
          name?: string;
          organization_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "import_mapping_presets_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      import_rows: {
        Row: {
          action: Database["public"]["Enums"]["import_row_action"] | null;
          batch_id: string;
          errors: NonNullable<Json>;
          id: string;
          mapped: Json | null;
          organization_id: string;
          raw: NonNullable<Json>;
          row_number: number;
          target_id: string | null;
          warnings: NonNullable<Json>;
        };
        Insert: {
          action?: Database["public"]["Enums"]["import_row_action"] | null;
          batch_id: string;
          errors?: NonNullable<Json>;
          id?: string;
          mapped?: Json | null;
          organization_id: string;
          raw: NonNullable<Json>;
          row_number: number;
          target_id?: string | null;
          warnings?: NonNullable<Json>;
        };
        Update: {
          action?: Database["public"]["Enums"]["import_row_action"] | null;
          batch_id?: string;
          errors?: NonNullable<Json>;
          id?: string;
          mapped?: Json | null;
          organization_id?: string;
          raw?: NonNullable<Json>;
          row_number?: number;
          target_id?: string | null;
          warnings?: NonNullable<Json>;
        };
        Relationships: [
          {
            foreignKeyName: "import_rows_organization_id_batch_id_fkey";
            columns: ["organization_id", "batch_id"];
            isOneToOne: false;
            referencedRelation: "import_batches";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      inventory_units: {
        Row: {
          acquired_on: string | null;
          condition_notes: string | null;
          created_at: string;
          id: string;
          label: string;
          organization_id: string;
          serial_number: string | null;
          status: string;
          updated_at: string;
          variant_id: string;
        };
        Insert: {
          acquired_on?: string | null;
          condition_notes?: string | null;
          created_at?: string;
          id?: string;
          label: string;
          organization_id: string;
          serial_number?: string | null;
          status?: string;
          updated_at?: string;
          variant_id: string;
        };
        Update: {
          acquired_on?: string | null;
          condition_notes?: string | null;
          created_at?: string;
          id?: string;
          label?: string;
          organization_id?: string;
          serial_number?: string | null;
          status?: string;
          updated_at?: string;
          variant_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "inventory_units_organization_id_variant_id_fkey";
            columns: ["organization_id", "variant_id"];
            isOneToOne: false;
            referencedRelation: "product_variants";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      organization_domains: {
        Row: {
          created_at: string;
          hostname: string;
          id: string;
          is_primary: boolean;
          organization_id: string;
          verified_at: string | null;
        };
        Insert: {
          created_at?: string;
          hostname: string;
          id?: string;
          is_primary?: boolean;
          organization_id: string;
          verified_at?: string | null;
        };
        Update: {
          created_at?: string;
          hostname?: string;
          id?: string;
          is_primary?: boolean;
          organization_id?: string;
          verified_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "organization_domains_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      organization_invitations: {
        Row: {
          accepted_at: string | null;
          accepted_by: string | null;
          created_at: string;
          email: string;
          expires_at: string;
          id: string;
          invited_by: string | null;
          organization_id: string;
          revoked_at: string | null;
          role: Database["public"]["Enums"]["org_role"];
          token_hash: string;
        };
        Insert: {
          accepted_at?: string | null;
          accepted_by?: string | null;
          created_at?: string;
          email: string;
          expires_at: string;
          id?: string;
          invited_by?: string | null;
          organization_id: string;
          revoked_at?: string | null;
          role: Database["public"]["Enums"]["org_role"];
          token_hash: string;
        };
        Update: {
          accepted_at?: string | null;
          accepted_by?: string | null;
          created_at?: string;
          email?: string;
          expires_at?: string;
          id?: string;
          invited_by?: string | null;
          organization_id?: string;
          revoked_at?: string | null;
          role?: Database["public"]["Enums"]["org_role"];
          token_hash?: string;
        };
        Relationships: [
          {
            foreignKeyName: "organization_invitations_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      organization_members: {
        Row: {
          created_at: string;
          organization_id: string;
          role: Database["public"]["Enums"]["org_role"];
          status: Database["public"]["Enums"]["member_status"];
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          organization_id: string;
          role: Database["public"]["Enums"]["org_role"];
          status?: Database["public"]["Enums"]["member_status"];
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          organization_id?: string;
          role?: Database["public"]["Enums"]["org_role"];
          status?: Database["public"]["Enums"]["member_status"];
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "organization_members_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      organization_policies: {
        Row: {
          body: string;
          created_at: string;
          id: string;
          is_placeholder: boolean;
          is_published: boolean;
          organization_id: string;
          policy_type: string;
          title: string;
          updated_at: string;
          version: number;
        };
        Insert: {
          body: string;
          created_at?: string;
          id?: string;
          is_placeholder?: boolean;
          is_published?: boolean;
          organization_id: string;
          policy_type: string;
          title: string;
          updated_at?: string;
          version?: number;
        };
        Update: {
          body?: string;
          created_at?: string;
          id?: string;
          is_placeholder?: boolean;
          is_published?: boolean;
          organization_id?: string;
          policy_type?: string;
          title?: string;
          updated_at?: string;
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: "organization_policies_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      organization_settings: {
        Row: {
          accent_color: string | null;
          address_line1: string | null;
          assistant_display_name: string | null;
          assistant_enabled: boolean;
          assistant_greeting: string | null;
          booking_hold_minutes: number;
          city: string | null;
          contact_email: string | null;
          contact_phone: string | null;
          created_at: string;
          default_event_start_time: string;
          default_rental_duration_minutes: number;
          default_setup_buffer_minutes: number;
          default_teardown_buffer_minutes: number;
          favicon_media_path: string | null;
          free_delivery_miles: number | null;
          logo_mark_media_path: string | null;
          logo_media_path: string | null;
          max_hold_renewals: number;
          max_rental_days: number;
          maximum_delivery_miles: number | null;
          mileage_basis: Database["public"]["Enums"]["mileage_basis"];
          mileage_rounding_method: Database["public"]["Enums"]["mileage_rounding"];
          min_booking_lead_time_minutes: number;
          organization_id: string;
          overnight_allowed: boolean;
          per_mile_rate_cents: number | null;
          postal_code: string | null;
          primary_color: string | null;
          primary_depot_address_line1: string | null;
          primary_depot_city: string | null;
          primary_depot_latitude: number | null;
          primary_depot_longitude: number | null;
          primary_depot_postal_code: string | null;
          primary_depot_state: string | null;
          quote_valid_days: number;
          secondary_color: string | null;
          sms_phone: string | null;
          state: string | null;
          updated_at: string;
          website_url: string | null;
        };
        Insert: {
          accent_color?: string | null;
          address_line1?: string | null;
          assistant_display_name?: string | null;
          assistant_enabled?: boolean;
          assistant_greeting?: string | null;
          booking_hold_minutes?: number;
          city?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          created_at?: string;
          default_event_start_time?: string;
          default_rental_duration_minutes?: number;
          default_setup_buffer_minutes?: number;
          default_teardown_buffer_minutes?: number;
          favicon_media_path?: string | null;
          free_delivery_miles?: number | null;
          logo_mark_media_path?: string | null;
          logo_media_path?: string | null;
          max_hold_renewals?: number;
          max_rental_days?: number;
          maximum_delivery_miles?: number | null;
          mileage_basis?: Database["public"]["Enums"]["mileage_basis"];
          mileage_rounding_method?: Database["public"]["Enums"]["mileage_rounding"];
          min_booking_lead_time_minutes?: number;
          organization_id: string;
          overnight_allowed?: boolean;
          per_mile_rate_cents?: number | null;
          postal_code?: string | null;
          primary_color?: string | null;
          primary_depot_address_line1?: string | null;
          primary_depot_city?: string | null;
          primary_depot_latitude?: number | null;
          primary_depot_longitude?: number | null;
          primary_depot_postal_code?: string | null;
          primary_depot_state?: string | null;
          quote_valid_days?: number;
          secondary_color?: string | null;
          sms_phone?: string | null;
          state?: string | null;
          updated_at?: string;
          website_url?: string | null;
        };
        Update: {
          accent_color?: string | null;
          address_line1?: string | null;
          assistant_display_name?: string | null;
          assistant_enabled?: boolean;
          assistant_greeting?: string | null;
          booking_hold_minutes?: number;
          city?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          created_at?: string;
          default_event_start_time?: string;
          default_rental_duration_minutes?: number;
          default_setup_buffer_minutes?: number;
          default_teardown_buffer_minutes?: number;
          favicon_media_path?: string | null;
          free_delivery_miles?: number | null;
          logo_mark_media_path?: string | null;
          logo_media_path?: string | null;
          max_hold_renewals?: number;
          max_rental_days?: number;
          maximum_delivery_miles?: number | null;
          mileage_basis?: Database["public"]["Enums"]["mileage_basis"];
          mileage_rounding_method?: Database["public"]["Enums"]["mileage_rounding"];
          min_booking_lead_time_minutes?: number;
          organization_id?: string;
          overnight_allowed?: boolean;
          per_mile_rate_cents?: number | null;
          postal_code?: string | null;
          primary_color?: string | null;
          primary_depot_address_line1?: string | null;
          primary_depot_city?: string | null;
          primary_depot_latitude?: number | null;
          primary_depot_longitude?: number | null;
          primary_depot_postal_code?: string | null;
          primary_depot_state?: string | null;
          quote_valid_days?: number;
          secondary_color?: string | null;
          sms_phone?: string | null;
          state?: string | null;
          updated_at?: string;
          website_url?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "organization_settings_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: true;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      organizations: {
        Row: {
          country_code: string;
          created_at: string;
          currency: string;
          id: string;
          legal_name: string | null;
          name: string;
          plan: string | null;
          slug: string;
          status: Database["public"]["Enums"]["org_status"];
          timezone: string;
          updated_at: string;
        };
        Insert: {
          country_code?: string;
          created_at?: string;
          currency?: string;
          id?: string;
          legal_name?: string | null;
          name: string;
          plan?: string | null;
          slug: string;
          status?: Database["public"]["Enums"]["org_status"];
          timezone?: string;
          updated_at?: string;
        };
        Update: {
          country_code?: string;
          created_at?: string;
          currency?: string;
          id?: string;
          legal_name?: string | null;
          name?: string;
          plan?: string | null;
          slug?: string;
          status?: Database["public"]["Enums"]["org_status"];
          timezone?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      product_categories: {
        Row: {
          category_id: string;
          organization_id: string;
          product_id: string;
        };
        Insert: {
          category_id: string;
          organization_id: string;
          product_id: string;
        };
        Update: {
          category_id?: string;
          organization_id?: string;
          product_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "product_categories_organization_id_category_id_fkey";
            columns: ["organization_id", "category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "product_categories_organization_id_category_id_fkey";
            columns: ["organization_id", "category_id"];
            isOneToOne: false;
            referencedRelation: "public_catalog_categories";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "product_categories_organization_id_product_id_fkey";
            columns: ["organization_id", "product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "product_categories_organization_id_product_id_fkey";
            columns: ["organization_id", "product_id"];
            isOneToOne: false;
            referencedRelation: "public_catalog_products";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      product_media: {
        Row: {
          alt_text: string | null;
          created_at: string;
          height: number | null;
          id: string;
          is_primary: boolean;
          kind: Database["public"]["Enums"]["media_kind"];
          organization_id: string;
          original_filename: string | null;
          product_id: string;
          rights_notes: string | null;
          rights_status: Database["public"]["Enums"]["media_rights_status"];
          sort_order: number;
          source: Database["public"]["Enums"]["media_source"];
          storage_path: string;
          storage_provider: string;
          updated_at: string;
          uploaded_by: string | null;
          width: number | null;
        };
        Insert: {
          alt_text?: string | null;
          created_at?: string;
          height?: number | null;
          id?: string;
          is_primary?: boolean;
          kind?: Database["public"]["Enums"]["media_kind"];
          organization_id: string;
          original_filename?: string | null;
          product_id: string;
          rights_notes?: string | null;
          rights_status?: Database["public"]["Enums"]["media_rights_status"];
          sort_order?: number;
          source: Database["public"]["Enums"]["media_source"];
          storage_path: string;
          storage_provider?: string;
          updated_at?: string;
          uploaded_by?: string | null;
          width?: number | null;
        };
        Update: {
          alt_text?: string | null;
          created_at?: string;
          height?: number | null;
          id?: string;
          is_primary?: boolean;
          kind?: Database["public"]["Enums"]["media_kind"];
          organization_id?: string;
          original_filename?: string | null;
          product_id?: string;
          rights_notes?: string | null;
          rights_status?: Database["public"]["Enums"]["media_rights_status"];
          sort_order?: number;
          source?: Database["public"]["Enums"]["media_source"];
          storage_path?: string;
          storage_provider?: string;
          updated_at?: string;
          uploaded_by?: string | null;
          width?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "product_media_organization_id_product_id_fkey";
            columns: ["organization_id", "product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "product_media_organization_id_product_id_fkey";
            columns: ["organization_id", "product_id"];
            isOneToOne: false;
            referencedRelation: "public_catalog_products";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      product_relations: {
        Row: {
          organization_id: string;
          product_id: string;
          related_product_id: string;
          relation_type: Database["public"]["Enums"]["product_relation_type"];
          sort_order: number;
        };
        Insert: {
          organization_id: string;
          product_id: string;
          related_product_id: string;
          relation_type: Database["public"]["Enums"]["product_relation_type"];
          sort_order?: number;
        };
        Update: {
          organization_id?: string;
          product_id?: string;
          related_product_id?: string;
          relation_type?: Database["public"]["Enums"]["product_relation_type"];
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "product_relations_organization_id_product_id_fkey";
            columns: ["organization_id", "product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "product_relations_organization_id_product_id_fkey";
            columns: ["organization_id", "product_id"];
            isOneToOne: false;
            referencedRelation: "public_catalog_products";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "product_relations_organization_id_related_product_id_fkey";
            columns: ["organization_id", "related_product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "product_relations_organization_id_related_product_id_fkey";
            columns: ["organization_id", "related_product_id"];
            isOneToOne: false;
            referencedRelation: "public_catalog_products";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      product_variants: {
        Row: {
          archived_at: string | null;
          created_at: string;
          id: string;
          is_active: boolean;
          is_default: boolean;
          name: string;
          organization_id: string;
          pooled_quantity: number | null;
          price_override_cents: number | null;
          product_id: string;
          setup_buffer_minutes: number | null;
          sku: string | null;
          teardown_buffer_minutes: number | null;
          tracking_mode: Database["public"]["Enums"]["tracking_mode"];
          updated_at: string;
        };
        Insert: {
          archived_at?: string | null;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          is_default?: boolean;
          name?: string;
          organization_id: string;
          pooled_quantity?: number | null;
          price_override_cents?: number | null;
          product_id: string;
          setup_buffer_minutes?: number | null;
          sku?: string | null;
          teardown_buffer_minutes?: number | null;
          tracking_mode?: Database["public"]["Enums"]["tracking_mode"];
          updated_at?: string;
        };
        Update: {
          archived_at?: string | null;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          is_default?: boolean;
          name?: string;
          organization_id?: string;
          pooled_quantity?: number | null;
          price_override_cents?: number | null;
          product_id?: string;
          setup_buffer_minutes?: number | null;
          sku?: string | null;
          teardown_buffer_minutes?: number | null;
          tracking_mode?: Database["public"]["Enums"]["tracking_mode"];
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "product_variants_organization_id_product_id_fkey";
            columns: ["organization_id", "product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "product_variants_organization_id_product_id_fkey";
            columns: ["organization_id", "product_id"];
            isOneToOne: false;
            referencedRelation: "public_catalog_products";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      products: {
        Row: {
          allowed_surfaces: string[];
          anchoring_methods: string[];
          archived_at: string | null;
          attendants_required: number;
          base_price_cents: number;
          created_at: string;
          description: string | null;
          dry_allowed: boolean;
          external_ref: string | null;
          external_source: string | null;
          extra_specs: NonNullable<Json>;
          id: string;
          ideal_event_types: Database["public"]["Enums"]["event_type"][];
          included_duration_minutes: number | null;
          indoor_allowed: boolean;
          internal_notes: string | null;
          is_featured: boolean;
          is_published: boolean;
          max_rider_weight_lbs: number | null;
          maximum_age: number | null;
          min_booking_lead_time_minutes: number | null;
          minimum_age: number | null;
          minimum_rental_minutes: number | null;
          name: string;
          operator_required: boolean;
          organization_id: string;
          outdoor_allowed: boolean;
          overnight_allowed: boolean | null;
          power_notes: string | null;
          power_outlets_required: number | null;
          pricing_type: Database["public"]["Enums"]["pricing_type"];
          primary_category_id: string | null;
          recommended_capacity: number | null;
          search_vector: unknown;
          setup_buffer_minutes: number | null;
          setup_minutes: number | null;
          setup_requirements: string | null;
          short_description: string | null;
          slug: string;
          sort_order: number;
          space_height_ft: number | null;
          space_length_ft: number | null;
          space_width_ft: number | null;
          tags: string[];
          teardown_buffer_minutes: number | null;
          teardown_minutes: number | null;
          updated_at: string;
          water_required: boolean;
          wet_allowed: boolean;
        };
        Insert: {
          allowed_surfaces?: string[];
          anchoring_methods?: string[];
          archived_at?: string | null;
          attendants_required?: number;
          base_price_cents: number;
          created_at?: string;
          description?: string | null;
          dry_allowed?: boolean;
          external_ref?: string | null;
          external_source?: string | null;
          extra_specs?: NonNullable<Json>;
          id?: string;
          ideal_event_types?: Database["public"]["Enums"]["event_type"][];
          included_duration_minutes?: number | null;
          indoor_allowed?: boolean;
          internal_notes?: string | null;
          is_featured?: boolean;
          is_published?: boolean;
          max_rider_weight_lbs?: number | null;
          maximum_age?: number | null;
          min_booking_lead_time_minutes?: number | null;
          minimum_age?: number | null;
          minimum_rental_minutes?: number | null;
          name: string;
          operator_required?: boolean;
          organization_id: string;
          outdoor_allowed?: boolean;
          overnight_allowed?: boolean | null;
          power_notes?: string | null;
          power_outlets_required?: number | null;
          pricing_type?: Database["public"]["Enums"]["pricing_type"];
          primary_category_id?: string | null;
          recommended_capacity?: number | null;
          search_vector?: never;
          setup_buffer_minutes?: number | null;
          setup_minutes?: number | null;
          setup_requirements?: string | null;
          short_description?: string | null;
          slug: string;
          sort_order?: number;
          space_height_ft?: number | null;
          space_length_ft?: number | null;
          space_width_ft?: number | null;
          tags?: string[];
          teardown_buffer_minutes?: number | null;
          teardown_minutes?: number | null;
          updated_at?: string;
          water_required?: boolean;
          wet_allowed?: boolean;
        };
        Update: {
          allowed_surfaces?: string[];
          anchoring_methods?: string[];
          archived_at?: string | null;
          attendants_required?: number;
          base_price_cents?: number;
          created_at?: string;
          description?: string | null;
          dry_allowed?: boolean;
          external_ref?: string | null;
          external_source?: string | null;
          extra_specs?: NonNullable<Json>;
          id?: string;
          ideal_event_types?: Database["public"]["Enums"]["event_type"][];
          included_duration_minutes?: number | null;
          indoor_allowed?: boolean;
          internal_notes?: string | null;
          is_featured?: boolean;
          is_published?: boolean;
          max_rider_weight_lbs?: number | null;
          maximum_age?: number | null;
          min_booking_lead_time_minutes?: number | null;
          minimum_age?: number | null;
          minimum_rental_minutes?: number | null;
          name?: string;
          operator_required?: boolean;
          organization_id?: string;
          outdoor_allowed?: boolean;
          overnight_allowed?: boolean | null;
          power_notes?: string | null;
          power_outlets_required?: number | null;
          pricing_type?: Database["public"]["Enums"]["pricing_type"];
          primary_category_id?: string | null;
          recommended_capacity?: number | null;
          search_vector?: never;
          setup_buffer_minutes?: number | null;
          setup_minutes?: number | null;
          setup_requirements?: string | null;
          short_description?: string | null;
          slug?: string;
          sort_order?: number;
          space_height_ft?: number | null;
          space_length_ft?: number | null;
          space_width_ft?: number | null;
          tags?: string[];
          teardown_buffer_minutes?: number | null;
          teardown_minutes?: number | null;
          updated_at?: string;
          water_required?: boolean;
          wet_allowed?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "products_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "products_organization_id_primary_category_id_fkey";
            columns: ["organization_id", "primary_category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "products_organization_id_primary_category_id_fkey";
            columns: ["organization_id", "primary_category_id"];
            isOneToOne: false;
            referencedRelation: "public_catalog_categories";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      reservation_allocations: {
        Row: {
          created_at: string;
          hold_expires_at: string | null;
          id: string;
          inventory_unit_id: string | null;
          occupied_period: unknown;
          organization_id: string;
          quantity: number;
          rental_period: unknown;
          reservation_id: string;
          status: Database["public"]["Enums"]["reservation_status"];
          variant_id: string;
        };
        Insert: {
          created_at?: string;
          hold_expires_at?: string | null;
          id?: string;
          inventory_unit_id?: string | null;
          occupied_period: unknown;
          organization_id: string;
          quantity?: number;
          rental_period: unknown;
          reservation_id: string;
          status: Database["public"]["Enums"]["reservation_status"];
          variant_id: string;
        };
        Update: {
          created_at?: string;
          hold_expires_at?: string | null;
          id?: string;
          inventory_unit_id?: string | null;
          occupied_period?: unknown;
          organization_id?: string;
          quantity?: number;
          rental_period?: unknown;
          reservation_id?: string;
          status?: Database["public"]["Enums"]["reservation_status"];
          variant_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reservation_allocations_organization_id_inventory_unit_id_fkey";
            columns: ["organization_id", "inventory_unit_id"];
            isOneToOne: false;
            referencedRelation: "inventory_units";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "reservation_allocations_organization_id_reservation_id_fkey";
            columns: ["organization_id", "reservation_id"];
            isOneToOne: false;
            referencedRelation: "reservations";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "reservation_allocations_organization_id_variant_id_fkey";
            columns: ["organization_id", "variant_id"];
            isOneToOne: false;
            referencedRelation: "product_variants";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      reservation_flags: {
        Row: {
          availability_block_id: string | null;
          created_at: string;
          id: string;
          kind: Database["public"]["Enums"]["reservation_flag_kind"];
          message: string;
          organization_id: string;
          reservation_id: string;
          resolved_at: string | null;
          resolved_by: string | null;
          status: string;
          weather_block_id: string | null;
        };
        Insert: {
          availability_block_id?: string | null;
          created_at?: string;
          id?: string;
          kind: Database["public"]["Enums"]["reservation_flag_kind"];
          message: string;
          organization_id: string;
          reservation_id: string;
          resolved_at?: string | null;
          resolved_by?: string | null;
          status?: string;
          weather_block_id?: string | null;
        };
        Update: {
          availability_block_id?: string | null;
          created_at?: string;
          id?: string;
          kind?: Database["public"]["Enums"]["reservation_flag_kind"];
          message?: string;
          organization_id?: string;
          reservation_id?: string;
          resolved_at?: string | null;
          resolved_by?: string | null;
          status?: string;
          weather_block_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "reservation_flags_organization_id_availability_block_id_fkey";
            columns: ["organization_id", "availability_block_id"];
            isOneToOne: false;
            referencedRelation: "availability_blocks";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "reservation_flags_organization_id_reservation_id_fkey";
            columns: ["organization_id", "reservation_id"];
            isOneToOne: false;
            referencedRelation: "reservations";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "reservation_flags_organization_id_weather_block_id_fkey";
            columns: ["organization_id", "weather_block_id"];
            isOneToOne: false;
            referencedRelation: "weather_blocks";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      reservations: {
        Row: {
          booking_request_id: string | null;
          confirmed_at: string | null;
          created_at: string;
          created_by: string | null;
          ended_at: string | null;
          event_id: string | null;
          hold_expires_at: string | null;
          hold_renewals: number;
          id: string;
          notes: string | null;
          organization_id: string;
          quote_id: string | null;
          replaced_by: string | null;
          source: Database["public"]["Enums"]["reservation_source"];
          status: Database["public"]["Enums"]["reservation_status"];
          updated_at: string;
        };
        Insert: {
          booking_request_id?: string | null;
          confirmed_at?: string | null;
          created_at?: string;
          created_by?: string | null;
          ended_at?: string | null;
          event_id?: string | null;
          hold_expires_at?: string | null;
          hold_renewals?: number;
          id?: string;
          notes?: string | null;
          organization_id: string;
          quote_id?: string | null;
          replaced_by?: string | null;
          source: Database["public"]["Enums"]["reservation_source"];
          status: Database["public"]["Enums"]["reservation_status"];
          updated_at?: string;
        };
        Update: {
          booking_request_id?: string | null;
          confirmed_at?: string | null;
          created_at?: string;
          created_by?: string | null;
          ended_at?: string | null;
          event_id?: string | null;
          hold_expires_at?: string | null;
          hold_renewals?: number;
          id?: string;
          notes?: string | null;
          organization_id?: string;
          quote_id?: string | null;
          replaced_by?: string | null;
          source?: Database["public"]["Enums"]["reservation_source"];
          status?: Database["public"]["Enums"]["reservation_status"];
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reservations_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      role_permissions: {
        Row: {
          permission: string;
          role: Database["public"]["Enums"]["org_role"];
        };
        Insert: {
          permission: string;
          role: Database["public"]["Enums"]["org_role"];
        };
        Update: {
          permission?: string;
          role?: Database["public"]["Enums"]["org_role"];
        };
        Relationships: [];
      };
      user_profiles: {
        Row: {
          avatar_path: string | null;
          created_at: string;
          full_name: string | null;
          id: string;
          phone: string | null;
          updated_at: string;
        };
        Insert: {
          avatar_path?: string | null;
          created_at?: string;
          full_name?: string | null;
          id: string;
          phone?: string | null;
          updated_at?: string;
        };
        Update: {
          avatar_path?: string | null;
          created_at?: string;
          full_name?: string | null;
          id?: string;
          phone?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      weather_block_targets: {
        Row: {
          category_id: string | null;
          organization_id: string;
          product_id: string | null;
          weather_block_id: string;
        };
        Insert: {
          category_id?: string | null;
          organization_id: string;
          product_id?: string | null;
          weather_block_id: string;
        };
        Update: {
          category_id?: string | null;
          organization_id?: string;
          product_id?: string | null;
          weather_block_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "weather_block_targets_organization_id_category_id_fkey";
            columns: ["organization_id", "category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "weather_block_targets_organization_id_category_id_fkey";
            columns: ["organization_id", "category_id"];
            isOneToOne: false;
            referencedRelation: "public_catalog_categories";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "weather_block_targets_organization_id_product_id_fkey";
            columns: ["organization_id", "product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "weather_block_targets_organization_id_product_id_fkey";
            columns: ["organization_id", "product_id"];
            isOneToOne: false;
            referencedRelation: "public_catalog_products";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "weather_block_targets_organization_id_weather_block_id_fkey";
            columns: ["organization_id", "weather_block_id"];
            isOneToOne: false;
            referencedRelation: "weather_blocks";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      weather_blocks: {
        Row: {
          confirmed_at: string | null;
          confirmed_by: string | null;
          created_at: string;
          created_by: string | null;
          hazard: Database["public"]["Enums"]["weather_hazard"];
          id: string;
          lifted_at: string | null;
          lifted_by: string | null;
          observed_unit: string | null;
          observed_value: number | null;
          organization_id: string;
          period: unknown;
          reason: string;
          scope: Database["public"]["Enums"]["weather_block_scope"];
          source: string;
          status: Database["public"]["Enums"]["weather_block_status"];
          updated_at: string;
        };
        Insert: {
          confirmed_at?: string | null;
          confirmed_by?: string | null;
          created_at?: string;
          created_by?: string | null;
          hazard: Database["public"]["Enums"]["weather_hazard"];
          id?: string;
          lifted_at?: string | null;
          lifted_by?: string | null;
          observed_unit?: string | null;
          observed_value?: number | null;
          organization_id: string;
          period: unknown;
          reason: string;
          scope?: Database["public"]["Enums"]["weather_block_scope"];
          source?: string;
          status?: Database["public"]["Enums"]["weather_block_status"];
          updated_at?: string;
        };
        Update: {
          confirmed_at?: string | null;
          confirmed_by?: string | null;
          created_at?: string;
          created_by?: string | null;
          hazard?: Database["public"]["Enums"]["weather_hazard"];
          id?: string;
          lifted_at?: string | null;
          lifted_by?: string | null;
          observed_unit?: string | null;
          observed_value?: number | null;
          organization_id?: string;
          period?: unknown;
          reason?: string;
          scope?: Database["public"]["Enums"]["weather_block_scope"];
          source?: string;
          status?: Database["public"]["Enums"]["weather_block_status"];
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "weather_blocks_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      weather_hazard_rules: {
        Row: {
          category_id: string | null;
          created_at: string;
          hazard: Database["public"]["Enums"]["weather_hazard"];
          id: string;
          notes: string | null;
          organization_id: string;
          product_id: string | null;
          sensitive: boolean;
          threshold_unit: string | null;
          threshold_value: number | null;
          updated_at: string;
        };
        Insert: {
          category_id?: string | null;
          created_at?: string;
          hazard: Database["public"]["Enums"]["weather_hazard"];
          id?: string;
          notes?: string | null;
          organization_id: string;
          product_id?: string | null;
          sensitive: boolean;
          threshold_unit?: string | null;
          threshold_value?: number | null;
          updated_at?: string;
        };
        Update: {
          category_id?: string | null;
          created_at?: string;
          hazard?: Database["public"]["Enums"]["weather_hazard"];
          id?: string;
          notes?: string | null;
          organization_id?: string;
          product_id?: string | null;
          sensitive?: boolean;
          threshold_unit?: string | null;
          threshold_value?: number | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "weather_hazard_rules_organization_id_category_id_fkey";
            columns: ["organization_id", "category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "weather_hazard_rules_organization_id_category_id_fkey";
            columns: ["organization_id", "category_id"];
            isOneToOne: false;
            referencedRelation: "public_catalog_categories";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "weather_hazard_rules_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "weather_hazard_rules_organization_id_product_id_fkey";
            columns: ["organization_id", "product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "weather_hazard_rules_organization_id_product_id_fkey";
            columns: ["organization_id", "product_id"];
            isOneToOne: false;
            referencedRelation: "public_catalog_products";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
    };
    Views: {
      public_catalog_categories: {
        Row: {
          description: string | null;
          id: string | null;
          name: string | null;
          organization_id: string | null;
          parent_id: string | null;
          slug: string | null;
          sort_order: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "categories_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "categories_organization_id_parent_id_fkey";
            columns: ["organization_id", "parent_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "categories_organization_id_parent_id_fkey";
            columns: ["organization_id", "parent_id"];
            isOneToOne: false;
            referencedRelation: "public_catalog_categories";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      public_catalog_product_media: {
        Row: {
          alt_text: string | null;
          height: number | null;
          id: string | null;
          is_primary: boolean | null;
          kind: Database["public"]["Enums"]["media_kind"] | null;
          organization_id: string | null;
          product_id: string | null;
          sort_order: number | null;
          storage_path: string | null;
          width: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "product_media_organization_id_product_id_fkey";
            columns: ["organization_id", "product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "product_media_organization_id_product_id_fkey";
            columns: ["organization_id", "product_id"];
            isOneToOne: false;
            referencedRelation: "public_catalog_products";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      public_catalog_products: {
        Row: {
          allowed_surfaces: string[] | null;
          anchoring_methods: string[] | null;
          attendants_required: number | null;
          base_price_cents: number | null;
          category_ids: string[] | null;
          description: string | null;
          dry_allowed: boolean | null;
          extra_specs: Json | null;
          id: string | null;
          ideal_event_types: Database["public"]["Enums"]["event_type"][] | null;
          included_duration_minutes: number | null;
          indoor_allowed: boolean | null;
          is_featured: boolean | null;
          max_rider_weight_lbs: number | null;
          maximum_age: number | null;
          minimum_age: number | null;
          minimum_rental_minutes: number | null;
          name: string | null;
          operator_required: boolean | null;
          organization_id: string | null;
          outdoor_allowed: boolean | null;
          power_notes: string | null;
          power_outlets_required: number | null;
          pricing_type: Database["public"]["Enums"]["pricing_type"] | null;
          primary_category_id: string | null;
          recommended_capacity: number | null;
          setup_requirements: string | null;
          short_description: string | null;
          slug: string | null;
          sort_order: number | null;
          space_height_ft: number | null;
          space_length_ft: number | null;
          space_width_ft: number | null;
          tags: string[] | null;
          water_required: boolean | null;
          weather_sensitivities: Json | null;
          wet_allowed: boolean | null;
        };
        Relationships: [
          {
            foreignKeyName: "products_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "products_organization_id_primary_category_id_fkey";
            columns: ["organization_id", "primary_category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "products_organization_id_primary_category_id_fkey";
            columns: ["organization_id", "primary_category_id"];
            isOneToOne: false;
            referencedRelation: "public_catalog_categories";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
    };
    Functions: {
      accept_invitation: { Args: { p_token: string }; Returns: string };
      check_availability: {
        Args: {
          p_end: string;
          p_organization_id: string;
          p_override_lead_time?: boolean;
          p_quantity?: number;
          p_start: string;
          p_variant_id: string;
        };
        Returns: {
          available: boolean;
          available_quantity: number;
          capacity: number;
          occupied_end: string;
          occupied_start: string;
          reasons: string[];
          requested_quantity: number;
        }[];
      };
      check_public_availability: {
        Args: {
          p_end: string;
          p_organization_id: string;
          p_quantity?: number;
          p_start: string;
          p_variant_id: string;
        };
        Returns: {
          available: boolean;
          limited: boolean;
          reasons: string[];
        }[];
      };
      commit_product_import: { Args: { p_batch_id: string }; Returns: Json };
      confirm_reservation: {
        Args: { p_ignore_weather?: boolean; p_reservation_id: string };
        Returns: undefined;
      };
      confirm_weather_block: { Args: { p_weather_block_id: string }; Returns: number };
      create_organization: {
        Args: {
          p_legal_name?: string;
          p_name: string;
          p_owner_user_id: string;
          p_slug: string;
          p_timezone: string;
        };
        Returns: string;
      };
      lift_weather_block: { Args: { p_weather_block_id: string }; Returns: undefined };
      record_audit_event: {
        Args: {
          p_action: string;
          p_entity_id?: string;
          p_entity_type: string;
          p_metadata?: Json;
          p_organization_id: string;
          p_request_id?: string;
        };
        Returns: number;
      };
      release_reservation: {
        Args: { p_reservation_id: string };
        Returns: Database["public"]["Enums"]["reservation_status"];
      };
      renew_hold: { Args: { p_reservation_id: string }; Returns: string };
      reserve_inventory: {
        Args: {
          p_items: Json;
          p_notes?: string;
          p_organization_id: string;
          p_override_lead_time?: boolean;
          p_replaces_reservation_id?: string;
          p_source?: Database["public"]["Enums"]["reservation_source"];
          p_status?: Database["public"]["Enums"]["reservation_status"];
        };
        Returns: string;
      };
      resolve_organization_by_host: {
        Args: { p_host: string };
        Returns: {
          accent_color: string;
          contact_email: string;
          contact_phone: string;
          currency: string;
          favicon_media_path: string;
          id: string;
          logo_mark_media_path: string;
          logo_media_path: string;
          name: string;
          primary_color: string;
          secondary_color: string;
          slug: string;
          sms_phone: string;
          timezone: string;
          website_url: string;
        }[];
      };
      resolve_organization_by_slug: {
        Args: { p_slug: string };
        Returns: {
          accent_color: string;
          contact_email: string;
          contact_phone: string;
          currency: string;
          favicon_media_path: string;
          id: string;
          logo_mark_media_path: string;
          logo_media_path: string;
          name: string;
          primary_color: string;
          secondary_color: string;
          slug: string;
          sms_phone: string;
          timezone: string;
          website_url: string;
        }[];
      };
      sweep_expired_holds: { Args: Record<PropertyKey, never>; Returns: number };
    };
    Enums: {
      audit_actor_type: "user" | "ai" | "system" | "public";
      block_reason: "blackout" | "maintenance" | "repair" | "private_use" | "staff_hold" | "other";
      event_type:
        | "birthday"
        | "school"
        | "church"
        | "corporate"
        | "community"
        | "graduation"
        | "festival"
        | "wedding"
        | "sports"
        | "holiday"
        | "other";
      import_row_action: "create" | "update" | "skip";
      import_status: "parsed" | "validated" | "committed" | "failed" | "cancelled";
      media_kind: "image" | "video";
      media_rights_status: "owned" | "licensed" | "supplier_permitted" | "unverified";
      media_source: "upload" | "import" | "supplier";
      member_status: "active" | "suspended";
      mileage_basis: "one_way" | "round_trip";
      mileage_rounding: "ceil_whole_mile" | "round_whole_mile" | "none";
      org_role: "owner" | "admin" | "office" | "staff";
      org_status: "onboarding" | "active" | "suspended" | "closed";
      pricing_type: "per_event" | "hourly" | "daily" | "per_unit";
      product_relation_type: "addon" | "recommended" | "requires";
      reservation_flag_kind: "availability_block" | "weather_block";
      reservation_source: "booking_request" | "manual" | "import";
      reservation_status: "held" | "confirmed" | "released" | "cancelled" | "completed";
      tracking_mode: "serialized" | "pooled";
      weather_block_scope: "all_sensitive" | "selected";
      weather_block_status: "proposed" | "confirmed" | "lifted";
      weather_hazard: "wind" | "lightning" | "rain" | "severe_weather" | "temperature" | "custom";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema["CompositeTypes"] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      audit_actor_type: ["user", "ai", "system", "public"],
      block_reason: ["blackout", "maintenance", "repair", "private_use", "staff_hold", "other"],
      event_type: [
        "birthday",
        "school",
        "church",
        "corporate",
        "community",
        "graduation",
        "festival",
        "wedding",
        "sports",
        "holiday",
        "other",
      ],
      import_row_action: ["create", "update", "skip"],
      import_status: ["parsed", "validated", "committed", "failed", "cancelled"],
      media_kind: ["image", "video"],
      media_rights_status: ["owned", "licensed", "supplier_permitted", "unverified"],
      media_source: ["upload", "import", "supplier"],
      member_status: ["active", "suspended"],
      mileage_basis: ["one_way", "round_trip"],
      mileage_rounding: ["ceil_whole_mile", "round_whole_mile", "none"],
      org_role: ["owner", "admin", "office", "staff"],
      org_status: ["onboarding", "active", "suspended", "closed"],
      pricing_type: ["per_event", "hourly", "daily", "per_unit"],
      product_relation_type: ["addon", "recommended", "requires"],
      reservation_flag_kind: ["availability_block", "weather_block"],
      reservation_source: ["booking_request", "manual", "import"],
      reservation_status: ["held", "confirmed", "released", "cancelled", "completed"],
      tracking_mode: ["serialized", "pooled"],
      weather_block_scope: ["all_sensitive", "selected"],
      weather_block_status: ["proposed", "confirmed", "lifted"],
      weather_hazard: ["wind", "lightning", "rain", "severe_weather", "temperature", "custom"],
    },
  },
} as const;
