// GENERATED by scripts/gen-types.sh from the database schema. Do not edit.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      audit_logs: {
        Row: {
          action: string;
          actor_type: Database["public"]["Enums"]["audit_actor_type"];
          actor_user_id: string | null;
          ai_action_id: string | null;
          changes: Json | null;
          created_at: string;
          entity_id: string | null;
          entity_type: string;
          id: number;
          ip_address: unknown;
          organization_id: string | null;
          request_id: string | null;
          user_agent: string | null;
        };
        Insert: {
          action: string;
          actor_type: Database["public"]["Enums"]["audit_actor_type"];
          actor_user_id?: string | null;
          ai_action_id?: string | null;
          changes?: Json | null;
          created_at?: string;
          entity_id?: string | null;
          entity_type: string;
          id?: never;
          ip_address?: unknown;
          organization_id?: string | null;
          request_id?: string | null;
          user_agent?: string | null;
        };
        Update: {
          action?: string;
          actor_type?: Database["public"]["Enums"]["audit_actor_type"];
          actor_user_id?: string | null;
          ai_action_id?: string | null;
          changes?: Json | null;
          created_at?: string;
          entity_id?: string | null;
          entity_type?: string;
          id?: never;
          ip_address?: unknown;
          organization_id?: string | null;
          request_id?: string | null;
          user_agent?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "audit_logs_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      organization_domains: {
        Row: {
          created_at: string;
          hostname: string;
          id: string;
          is_primary: boolean;
          organization_id: string;
          verified_at: string | null;
        };
        Insert: {
          created_at?: string;
          hostname: string;
          id?: string;
          is_primary?: boolean;
          organization_id: string;
          verified_at?: string | null;
        };
        Update: {
          created_at?: string;
          hostname?: string;
          id?: string;
          is_primary?: boolean;
          organization_id?: string;
          verified_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "organization_domains_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      organization_invitations: {
        Row: {
          accepted_at: string | null;
          accepted_by: string | null;
          created_at: string;
          email: string;
          expires_at: string;
          id: string;
          invited_by: string | null;
          organization_id: string;
          revoked_at: string | null;
          role: Database["public"]["Enums"]["org_role"];
          token_hash: string;
        };
        Insert: {
          accepted_at?: string | null;
          accepted_by?: string | null;
          created_at?: string;
          email: string;
          expires_at: string;
          id?: string;
          invited_by?: string | null;
          organization_id: string;
          revoked_at?: string | null;
          role: Database["public"]["Enums"]["org_role"];
          token_hash: string;
        };
        Update: {
          accepted_at?: string | null;
          accepted_by?: string | null;
          created_at?: string;
          email?: string;
          expires_at?: string;
          id?: string;
          invited_by?: string | null;
          organization_id?: string;
          revoked_at?: string | null;
          role?: Database["public"]["Enums"]["org_role"];
          token_hash?: string;
        };
        Relationships: [
          {
            foreignKeyName: "organization_invitations_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      organization_members: {
        Row: {
          created_at: string;
          organization_id: string;
          role: Database["public"]["Enums"]["org_role"];
          status: Database["public"]["Enums"]["member_status"];
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          organization_id: string;
          role: Database["public"]["Enums"]["org_role"];
          status?: Database["public"]["Enums"]["member_status"];
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          organization_id?: string;
          role?: Database["public"]["Enums"]["org_role"];
          status?: Database["public"]["Enums"]["member_status"];
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "organization_members_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      organization_policies: {
        Row: {
          body: string;
          created_at: string;
          id: string;
          is_published: boolean;
          organization_id: string;
          policy_type: string;
          title: string;
          updated_at: string;
          version: number;
        };
        Insert: {
          body: string;
          created_at?: string;
          id?: string;
          is_published?: boolean;
          organization_id: string;
          policy_type: string;
          title: string;
          updated_at?: string;
          version?: number;
        };
        Update: {
          body?: string;
          created_at?: string;
          id?: string;
          is_published?: boolean;
          organization_id?: string;
          policy_type?: string;
          title?: string;
          updated_at?: string;
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: "organization_policies_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      organization_settings: {
        Row: {
          address_line1: string | null;
          assistant_display_name: string | null;
          assistant_enabled: boolean;
          assistant_greeting: string | null;
          booking_hold_minutes: number;
          city: string | null;
          contact_email: string | null;
          contact_phone: string | null;
          created_at: string;
          default_event_start_time: string;
          default_rental_duration_minutes: number;
          default_setup_buffer_minutes: number;
          default_teardown_buffer_minutes: number;
          depot_address_line1: string | null;
          depot_city: string | null;
          depot_latitude: number | null;
          depot_longitude: number | null;
          depot_postal_code: string | null;
          depot_state: string | null;
          logo_media_path: string | null;
          max_wind_mph: number | null;
          min_booking_lead_time_minutes: number;
          organization_id: string;
          overnight_allowed: boolean;
          postal_code: string | null;
          primary_color: string | null;
          quote_valid_days: number;
          secondary_color: string | null;
          sms_phone: string | null;
          state: string | null;
          updated_at: string;
          website_url: string | null;
        };
        Insert: {
          address_line1?: string | null;
          assistant_display_name?: string | null;
          assistant_enabled?: boolean;
          assistant_greeting?: string | null;
          booking_hold_minutes?: number;
          city?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          created_at?: string;
          default_event_start_time?: string;
          default_rental_duration_minutes?: number;
          default_setup_buffer_minutes?: number;
          default_teardown_buffer_minutes?: number;
          depot_address_line1?: string | null;
          depot_city?: string | null;
          depot_latitude?: number | null;
          depot_longitude?: number | null;
          depot_postal_code?: string | null;
          depot_state?: string | null;
          logo_media_path?: string | null;
          max_wind_mph?: number | null;
          min_booking_lead_time_minutes?: number;
          organization_id: string;
          overnight_allowed?: boolean;
          postal_code?: string | null;
          primary_color?: string | null;
          quote_valid_days?: number;
          secondary_color?: string | null;
          sms_phone?: string | null;
          state?: string | null;
          updated_at?: string;
          website_url?: string | null;
        };
        Update: {
          address_line1?: string | null;
          assistant_display_name?: string | null;
          assistant_enabled?: boolean;
          assistant_greeting?: string | null;
          booking_hold_minutes?: number;
          city?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          created_at?: string;
          default_event_start_time?: string;
          default_rental_duration_minutes?: number;
          default_setup_buffer_minutes?: number;
          default_teardown_buffer_minutes?: number;
          depot_address_line1?: string | null;
          depot_city?: string | null;
          depot_latitude?: number | null;
          depot_longitude?: number | null;
          depot_postal_code?: string | null;
          depot_state?: string | null;
          logo_media_path?: string | null;
          max_wind_mph?: number | null;
          min_booking_lead_time_minutes?: number;
          organization_id?: string;
          overnight_allowed?: boolean;
          postal_code?: string | null;
          primary_color?: string | null;
          quote_valid_days?: number;
          secondary_color?: string | null;
          sms_phone?: string | null;
          state?: string | null;
          updated_at?: string;
          website_url?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "organization_settings_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: true;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      organizations: {
        Row: {
          country_code: string;
          created_at: string;
          currency: string;
          id: string;
          legal_name: string | null;
          name: string;
          plan: string | null;
          slug: string;
          status: Database["public"]["Enums"]["org_status"];
          timezone: string;
          updated_at: string;
        };
        Insert: {
          country_code?: string;
          created_at?: string;
          currency?: string;
          id?: string;
          legal_name?: string | null;
          name: string;
          plan?: string | null;
          slug: string;
          status?: Database["public"]["Enums"]["org_status"];
          timezone?: string;
          updated_at?: string;
        };
        Update: {
          country_code?: string;
          created_at?: string;
          currency?: string;
          id?: string;
          legal_name?: string | null;
          name?: string;
          plan?: string | null;
          slug?: string;
          status?: Database["public"]["Enums"]["org_status"];
          timezone?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      role_permissions: {
        Row: {
          permission: string;
          role: Database["public"]["Enums"]["org_role"];
        };
        Insert: {
          permission: string;
          role: Database["public"]["Enums"]["org_role"];
        };
        Update: {
          permission?: string;
          role?: Database["public"]["Enums"]["org_role"];
        };
        Relationships: [];
      };
      user_profiles: {
        Row: {
          avatar_path: string | null;
          created_at: string;
          full_name: string | null;
          id: string;
          phone: string | null;
          updated_at: string;
        };
        Insert: {
          avatar_path?: string | null;
          created_at?: string;
          full_name?: string | null;
          id: string;
          phone?: string | null;
          updated_at?: string;
        };
        Update: {
          avatar_path?: string | null;
          created_at?: string;
          full_name?: string | null;
          id?: string;
          phone?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      accept_invitation: { Args: { p_token: string }; Returns: string };
      create_organization: {
        Args: {
          p_legal_name?: string;
          p_name: string;
          p_owner_user_id: string;
          p_slug: string;
          p_timezone: string;
        };
        Returns: string;
      };
      record_audit_event: {
        Args: {
          p_action: string;
          p_entity_id?: string;
          p_entity_type: string;
          p_metadata?: Json;
          p_organization_id: string;
          p_request_id?: string;
        };
        Returns: number;
      };
      resolve_organization_by_host: {
        Args: { p_host: string };
        Returns: {
          contact_email: string;
          contact_phone: string;
          currency: string;
          id: string;
          logo_media_path: string;
          name: string;
          primary_color: string;
          secondary_color: string;
          slug: string;
          timezone: string;
        }[];
      };
      resolve_organization_by_slug: {
        Args: { p_slug: string };
        Returns: {
          contact_email: string;
          contact_phone: string;
          currency: string;
          id: string;
          logo_media_path: string;
          name: string;
          primary_color: string;
          secondary_color: string;
          slug: string;
          timezone: string;
        }[];
      };
    };
    Enums: {
      audit_actor_type: "user" | "ai" | "system" | "public";
      member_status: "active" | "suspended";
      org_role: "owner" | "admin" | "office" | "staff";
      org_status: "onboarding" | "active" | "suspended" | "closed";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema["CompositeTypes"] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      audit_actor_type: ["user", "ai", "system", "public"],
      member_status: ["active", "suspended"],
      org_role: ["owner", "admin", "office", "staff"],
      org_status: ["onboarding", "active", "suspended", "closed"],
    },
  },
} as const;
