#!/usr/bin/env bash
# Regenerate src/types/database.ts from the database schema. Never edit that file by hand.
#   With the Supabase stack running:   pnpm db:types
#   Against any Postgres (ADR 0007):   DATABASE_URL=postgresql://... pnpm db:types
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/src/types/database.ts"
if [[ -n "${DATABASE_URL:-}" ]]; then
  SOURCE=(--db-url "$DATABASE_URL")
else
  SOURCE=(--local)
fi
{
  echo "// GENERATED by scripts/gen-types.sh from the database schema. Do not edit."
  pnpm exec supabase gen types typescript "${SOURCE[@]}" --schema public 2>/dev/null \
    | pnpm exec prettier --stdin-filepath generated.ts
} > "$OUT.tmp"
mv "$OUT.tmp" "$OUT"
echo "Wrote $OUT"
