import type { ImportAdapter } from "./types";

/** Any spreadsheet exported to CSV. Matches common, plain-English column names. */
export const genericCsvAdapter: ImportAdapter = {
  id: "generic_csv",
  label: "Spreadsheet (CSV)",
  externalSource: "csv",
  verified: true,
  headerSynonyms: {
    external_ref: ["id", "sku", "item id", "product id", "external id"],
    name: ["name", "product name", "item name", "title", "product"],
    slug: ["slug", "url slug"],
    short_description: ["short description", "summary", "tagline"],
    description: ["description", "long description", "details"],
    base_price: ["price", "base price", "rental price", "rate"],
    included_hours: ["hours", "included hours", "rental hours", "duration hours"],
    category: ["category", "categories", "type"],
    quantity: ["quantity", "qty", "count", "units", "stock"],
    tracking_mode: ["inventory type", "tracking"],
    is_published: ["published", "active", "visible", "online"],
    wet_allowed: ["wet", "wet ok", "wet allowed"],
    dry_allowed: ["dry", "dry ok", "dry allowed"],
    minimum_age: ["min age", "minimum age", "age min"],
    maximum_age: ["max age", "maximum age", "age max"],
    recommended_capacity: ["capacity", "max riders", "riders"],
    max_rider_weight_lbs: ["max weight", "weight limit"],
    dimensions: ["dimensions", "size", "footprint"],
    space_length_ft: ["length", "length ft"],
    space_width_ft: ["width", "width ft"],
    space_height_ft: ["height", "height ft"],
    power_outlets_required: ["outlets", "outlets required", "power outlets"],
    power_notes: ["power", "power notes", "power requirements"],
    water_required: ["water required", "needs water", "water hookup"],
    operator_required: ["operator required", "needs operator"],
    attendants_required: ["attendants", "attendants required", "staff required"],
    setup_minutes: ["setup minutes", "setup time"],
    teardown_minutes: ["teardown minutes", "teardown time"],
    setup_requirements: ["setup requirements", "setup notes"],
    indoor_allowed: ["indoor", "indoor ok"],
    outdoor_allowed: ["outdoor", "outdoor ok"],
    wind_sensitive: ["wind sensitive"],
    event_types: ["event types", "ideal for", "occasions"],
    tags: ["tags", "keywords"],
    internal_notes: ["internal notes", "notes", "staff notes"],
  },
};
